name: PyInstaller Windows Build

on:
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          pip install -r src/requirements.txt
          pip install pyinstaller

      - name: Generate Tag and Name
        id: meta
        run: |
          $date = Get-Date -Format "yyyy.MM.dd-HHmm"
          echo "tag=v$date" >> $env:GITHUB_OUTPUT

      - name: Build Executable
        run: |
          pyinstaller --onefile `
            --name run-${{ steps.meta.outputs.tag }} `
            --distpath dist `
            --hidden-import=PySide6 `
            --hidden-import=PySide6.QtCore `
            --hidden-import=PySide6.QtWidgets `
            --hidden-import=PySide6.QtGui `
            --hidden-import=PySide6.QtNetwork `
            --collect-all PySide6 `
            --collect-all shiboken6 `
            --copy-metadata PySide6 `
            src/run.py

      - name: Create Draft Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.meta.outputs.tag }}
          name: ${{ steps.meta.outputs.tag }}
          draft: true
          files: ./dist/run-${{ steps.meta.outputs.tag }}.exe
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
